stages:
  split:
    cmd: python split.py phrases.csv phrases-train.csv phrases-test.csv
    deps:
    - phrases.csv
    - split.py
    outs:
    - phrases-test.csv
    - phrases-train.csv
  featurize:
    cmd: python featurize.py phrases-train.csv phrases-train-feats.csv
    deps:
    - featurize.py
    - phrases-train.csv
    outs:
    - phrases-train-feats.csv
  train:
    cmd: python train.py phrases-train-feats.csv model.json
    deps:
    - phrases-train-feats.csv
    - train.py
    outs:
    - model.json
  evaluate:
    cmd: python evaluate.py model.json phrases-test.csv
    deps:
    - evaluate.py
    - model.json
    - phrases-test.csv
    metrics:
    - metrics.json:
        cache: false
