stages:
  split:
    cmd: python split.py documents.csv documents-train.csv documents-test.csv
    deps:
    - documents.csv
    - split.py
    outs:
    - documents-test.csv
    - documents-train.csv
  featurize:
    cmd: python featurize.py documents-train.csv documents-train-feats.csv
    deps:
    - documents-train.csv
    - featurize.py
    outs:
    - documents-train-feats.csv
  train:
    cmd: python train.py documents-train-feats.csv model.json
    deps:
    - documents-train-feats.csv
    - train.py
    outs:
    - model.json
  evaluate:
    cmd: python evaluate.py model.json documents-test.csv
    deps:
    - documents-test.csv
    - evaluate.py
    - model.json
    metrics:
    - metrics.json:
        cache: false
